import { create } from 'zustand';

export type Language = 'en' | 'ar';

export interface LanguageState {
  lang: Language;
  dir: 'ltr' | 'rtl';
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Brand & App
    brandName: 'AVELYNQ',
    tagline: 'Built to Grow. Designed to Endure.',
    taglineSub: 'صُمم لينمو. وبُني ليصمد.',
    systemOverview: 'Enterprise Resource Planning & System Continuity',
    continuity: 'Continuity',
    structure: 'Structure',
    scalability: 'Scalability',
    dashboardTitle: 'System Command Center',
    dashboardBreadcrumb: 'Enterprise / Overview',
    languageToggle: 'العربية',
    searchPlaceholder: 'Search by code, title, or reference...',
    close: 'Close',
    openMenu: 'Open navigation',

    // Auth & Navigation
    login: 'Login',
    signup: 'Create Account',
    activateAccount: 'Activate Account',
    forgotPassword: 'Forgot Password?',
    resetPassword: 'Reset Password',
    backToLogin: 'Back to Login',
    logout: 'Sign Out',
    welcomeBack: 'Welcome to AVELYNQ ERP',
    loginSubtitle: 'Enter your enterprise credentials to access your organization modules.',
    username: 'Username or Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    fullName: 'Full Name',
    email: 'Work Email Address',
    activationCode: 'Activation Code / Token',
    otpCode: 'Verification OTP Code',
    newPassword: 'New Password',
    rememberMe: 'Remember this device',
    role: 'Operating Role',
    admin: 'System Administrator',
    financeManager: 'Finance Manager',
    hrOfficer: 'HR Specialist',
    enterWorkspace: 'Sign In to ERP',
    submitAccountCreation: 'Submit Registration',
    submitActivation: 'Activate Account',
    submitPasswordResetReq: 'Send Reset Link',
    submitNewPassword: 'Save New Password',
    authWelcomeDesc: 'Access unified enterprise operations across financial, organizational, and security domains.',
    haveAccount: 'Already have an account?',
    dontHaveAccount: 'Need an account?',
    enterOtpSent: 'Enter the verification OTP sent to your registered channel.',

    // Navigation Groups & Items
    groupGeneral: 'GENERAL',
    groupSecurity: 'SECURITY & RBAC',
    groupOrganization: 'ORGANIZATION',
    groupNotifications: 'NOTIFICATIONS',
    groupSystem: 'SYSTEM CONTROL',

    navOverview: 'Overview',
    navUsers: 'User Management',
    navRoles: 'Roles & Permissions',
    navPermissions: 'Permission Registry',
    navPages: 'Page Registry',
    navLegalEntities: 'Legal Entities',
    navBranches: 'Branches',
    navRegions: 'Regions',
    navDepartments: 'Departments Tree',
    navCostCenters: 'Cost Centers Tree',
    navProfitCenters: 'Profit Centers',
    navLocationSites: 'Location Sites',
    navNotificationInbox: 'Notification Inbox',
    navNotificationTemplates: 'Notification Templates',
    navNotificationChannels: 'Channel Configuration',

    // Shared Actions & Buttons
    search: 'Search...',
    new: 'Add New',
    filters: 'Filters',
    clear: 'Clear',
    export: 'Export Data',
    save: 'Save Changes',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    view: 'View Details',
    actions: 'Actions',
    status: 'Status',
    type: 'Type',
    code: 'Code',
    name: 'Name',
    description: 'Description',
    notes: 'Notes / Remarks',
    active: 'Active',
    inactive: 'Inactive',
    all: 'All',
    enabled: 'Enabled',
    disabled: 'Disabled',
    details: 'Details',
    confirm: 'Confirm',
    add: 'Add',
    remove: 'Remove',
    syncAll: 'Sync All',
    copyFrom: 'Copy From Role',
    markAsRead: 'Mark as Read',
    markAllAsRead: 'Mark All Read',
    viewAll: 'View All',
    userProfile: 'User Profile',
    dataScope: 'Branch Data Scope',
    viewBranches: 'View Branches',
    addRoot: 'Add Root Node',
    addChild: 'Add Child',
    expandAll: 'Expand All',
    collapseAll: 'Collapse All',
    selected: 'Selected',
    readOnlyCodeHint: 'System code is automatically assigned and immutable post-creation.',
    requiredFieldHint: 'Fields marked with (*) are mandatory.',
    bilingualRequiredHint: 'Both English and Arabic names are required.',

    // Data Grid & Stats
    totalRecords: 'Total Records',
    activeRecords: 'Active Records',
    inactiveRecords: 'Inactive Records',
    totalUsers: 'Total Users',
    activeUsers: 'Active Users',
    totalRoles: 'Configured Roles',
    totalEntities: 'Legal Entities',
    totalBranches: 'Active Branches',
    totalDepartments: 'Total Departments',
    totalCostCenters: 'Cost Centers',
    unreadNotifications: 'Unread Alerts',
    activeTemplates: 'Active Templates',
    activeChannels: 'Enabled Channels',
    showing: 'Showing',
    of: 'of',
    items: 'items',
    noRecordsFound: 'No records found',
    noRecordsDesc: 'Try adjusting your search criteria or add a new record.',
    selectBranchToLoadTree: 'Please select a branch to view and manage its organizational hierarchy.',

    // Security Module Specific
    secUsersTitle: 'Enterprise User Directory',
    secUsersBreadcrumb: 'Security / Users',
    secRolesTitle: 'Role-Based Access Control (RBAC)',
    secRolesBreadcrumb: 'Security / Roles & Matrix',
    secPermsTitle: 'System Permission Registry',
    secPermsBreadcrumb: 'Security / Permissions',
    secPagesTitle: 'Page & Screen Registry',
    secPagesBreadcrumb: 'Security / Pages',
    secProfileTitle: 'User Profile Details',
    secDataScopeTitle: 'Role Data Scope & Branch Assignment',
    userRoles: 'Assigned Roles',
    permissionMatrix: 'Permission Matrix',
    permType: 'Permission Type',
    permNameHint: 'Format: PERM_<MODULE>_<ACTION>',
    autoPermsNotice: 'Saving this page will automatically generate VIEW, CREATE, UPDATE, and DELETE permissions.',
    canView: 'View',
    canCreate: 'Create',
    canUpdate: 'Update',
    canDelete: 'Delete',
    activateRole: 'Activate Role',
    deactivateRole: 'Deactivate Role',
    reactivate: 'Reactivate',
    deactivate: 'Deactivate',
    employeeId: 'Employee ID',
    preferredLang: 'Preferred Language',
    assignedBranch: 'Assigned Branch',
    dataAccessLevel: 'Data Access Level',
    branchOnly: 'Branch Only',
    branchAndChildren: 'Branch & Child Units',
    allBranches: 'All Organization Branches',
    fullNameEn: 'Full Name (English)',
    fullNameAr: 'Full Name (Arabic)',
    nameEn: 'Name (English)',
    nameAr: 'Name (Arabic)',

    // Organization Module Specific
    orgEntitiesTitle: 'Legal Entities Management',
    orgEntitiesBreadcrumb: 'Organization / Legal Entities',
    orgBranchesTitle: 'Corporate Branch Directory',
    orgBranchesBreadcrumb: 'Organization / Branches',
    orgRegionsTitle: 'Geographic Regions',
    orgRegionsBreadcrumb: 'Organization / Regions',
    orgDeptsTitle: 'Department Structure & Hierarchy',
    orgDeptsBreadcrumb: 'Organization / Departments',
    orgCostCentersTitle: 'Cost Center Trees',
    orgCostCentersBreadcrumb: 'Organization / Cost Centers',
    orgProfitCentersTitle: 'Profit Centers',
    orgProfitCentersBreadcrumb: 'Organization / Profit Centers',
    orgLocationsTitle: 'Location Sites & Facilities',
    orgLocationsBreadcrumb: 'Organization / Locations',
    entityType: 'Entity Type',
    branchType: 'Branch Type',
    regionType: 'Region Region LOV',
    costCenterType: 'Cost Center Classification',
    siteType: 'Site Facility Type',
    nodeType: 'Node Type (Summary / Detail)',
    parentDepartment: 'Parent Department',
    parentCostCenter: 'Parent Cost Center',
    legalEntity: 'Legal Entity',
    branch: 'Branch',
    summaryNode: 'Summary (Parent)',
    detailNode: 'Detail (Posting/Leaf)',
    nodeTypeLockedHint: 'Node type cannot be altered once created.',
    cascadeDeactivateWarning: 'Cannot deactivate entity: active branch dependencies exist.',
    cascadeBranchWarning: 'Deactivating this branch affects associated departments and locations.',

    // File Service Specific
    fileAttachments: 'File Attachments & Documents',
    uploadFile: 'Upload Document',
    dragDropFile: 'Drag & drop files here or click to browse',
    maxFileSize: 'Maximum file size: 5MB (PDF, DOCX, PNG, JPG)',
    fileCategory: 'Document Category',
    fileSize: 'Size',
    uploadDate: 'Uploaded Date',
    download: 'Download',
    uploading: 'Uploading document...',
    noFilesFound: 'No files attached yet',
    noFilesDesc: 'Upload supporting contracts, certificates, or operational files.',

    // Notifications Module Specific
    notifInboxTitle: 'System Notification Inbox',
    notifInboxBreadcrumb: 'Notifications / Inbox & Logs',
    notifTemplatesTitle: 'Notification Templates',
    notifTemplatesBreadcrumb: 'Notifications / Templates',
    notifChannelsTitle: 'Communication Channels',
    notifChannelsBreadcrumb: 'Notifications / Channels',
    templateCode: 'Template Code',
    templateName: 'Template Name',
    channel: 'Channel',
    module: 'Module',
    bodyEn: 'Message Body (English)',
    bodyAr: 'Message Body (Arabic)',
    templateBodyRequired: 'Both English and Arabic templates must contain message bodies.',
    availablePlaceholders: 'Available Placeholders: {{username}}, {{branchName}}, {{otpCode}}, {{unitCode}}',
    editJsonConfig: 'Edit JSON Configuration',
    channelDisabledWarning: 'Disabling this channel will halt all automated dispatch via this gateway.',

    // Confirmation & Alerts
    confirmActionTitle: 'Confirm Required Action',
    confirmDeleteUser: 'Are you sure you want to permanently remove this user account?',
    confirmDeactivate: 'Are you sure you want to deactivate this record?',
    confirmReactivate: 'Are you sure you want to reactivate this record?',
    confirmDeleteFile: 'Are you sure you want to remove this attached file?',
    confirmToggleChannel: 'Are you sure you want to change the operating status of this communication channel?',
  },
  ar: {
    // Brand & App
    brandName: 'أفيلينك',
    tagline: 'صُمم لينمو. وبُني ليصمد.',
    taglineSub: 'Built to Grow. Designed to Endure.',
    systemOverview: 'تخطيط الموارد المؤسسية واستدامة الأنظمة',
    continuity: 'الاستدامة',
    structure: 'الهيكلية',
    scalability: 'القابلية للتوسع',
    dashboardTitle: 'مركز التحكم والعمليات الرئيسي',
    dashboardBreadcrumb: 'المنظومة / نظرة عامة',
    languageToggle: 'English',
    searchPlaceholder: 'البحث بالرمز، العنوان، أو المرجع...',
    close: 'إغلاق',
    openMenu: 'فتح القائمة',

    // Auth & Navigation
    login: 'تسجيل الدخول',
    signup: 'إنشاء حساب جديد',
    activateAccount: 'تفعيل الحساب',
    forgotPassword: 'نسيت كلمة المرور؟',
    resetPassword: 'إعادة تعيين كلمة المرور',
    backToLogin: 'العودة لتسجيل الدخول',
    logout: 'تسجيل الخروج',
    welcomeBack: 'مرحباً بك في أفيلينك لتخطيط الموارد',
    loginSubtitle: 'أدخل بيانات الاعتماد المؤسسية الخاصة بك للوصول إلى لوحة التحكم.',
    username: 'اسم المستخدم أو البريد',
    password: 'كلمة المرور',
    confirmPassword: 'تأكيد كلمة المرور',
    fullName: 'الاسم الكامل',
    email: 'البريد الإلكتروني المهني',
    activationCode: 'رمز أو مفتاح التفعيل',
    otpCode: 'رمز التحقق (OTP)',
    newPassword: 'كلمة المرور الجديدة',
    rememberMe: 'تذكر هذا الجهاز',
    role: 'الدور التشغيلي',
    admin: 'مسؤول النظام الرئيسي',
    financeManager: 'مدير الشؤون المالية',
    hrOfficer: 'أخصائي الموارد البشرية',
    enterWorkspace: 'دخول لوحة التحكم',
    submitAccountCreation: 'إرسال طلب التسجيل',
    submitActivation: 'تفعيل الحساب',
    submitPasswordResetReq: 'إرسال رابط الاستعادة',
    submitNewPassword: 'حفظ كلمة المرور الجديدة',
    authWelcomeDesc: 'إدارة متكاملة للعمليات المؤسسية عبر الشؤون المالية والتنظيمية والأمنية.',
    haveAccount: 'لديك حساب بالفعل؟',
    dontHaveAccount: 'ليس لديك حساب؟',
    enterOtpSent: 'أدخل رمز التحقق المرسل إلى قناة الاتصال المعتمدة.',

    // Navigation Groups & Items
    groupGeneral: 'عام',
    groupSecurity: 'الأمن وإدارة الصلاحيات',
    groupOrganization: 'الهيكل التنظيمي',
    groupNotifications: 'مركز الإشعارات',
    groupSystem: 'إدارة النظام',

    navOverview: 'نظرة عامة',
    navUsers: 'إدارة المستخدمين',
    navRoles: 'الأدوار والصلاحيات',
    navPermissions: 'سجل الصلاحيات',
    navPages: 'سجل الشاشات',
    navLegalEntities: 'الكيانات القانونية',
    navBranches: 'الفروع المؤسسية',
    navRegions: 'المناطق الجغرافية',
    navDepartments: 'شجرة الأقسام والهيكل',
    navCostCenters: 'شجرة مراكز التكلفة',
    navProfitCenters: 'مراكز الربحية',
    navLocationSites: 'المواقع والمستودعات',
    navNotificationInbox: 'صندوق الإشعارات',
    navNotificationTemplates: 'قوالب الإشعارات',
    navNotificationChannels: 'تهيئة قنوات الإرسال',

    // Shared Actions & Buttons
    search: 'بحث...',
    new: 'إضافة جديد',
    filters: 'تصفية',
    clear: 'مسح',
    export: 'تصدير البيانات',
    save: 'حفظ التعديلات',
    cancel: 'إلغاء',
    edit: 'تعديل',
    delete: 'حذف',
    view: 'عرض التفاصيل',
    actions: 'الإجراءات',
    status: 'الحالة',
    type: 'النوع',
    code: 'الرمز',
    name: 'الاسم',
    description: 'الوصف',
    notes: 'الملاحظات / البيان',
    active: 'نشط',
    inactive: 'غير نشط',
    all: 'الكل',
    enabled: 'مفعل',
    disabled: 'معطل',
    details: 'التفاصيل',
    confirm: 'تأكيد',
    add: 'إضافة',
    remove: 'إزالة',
    syncAll: 'تحديد الكل',
    copyFrom: 'نسخ من دور آخر',
    markAsRead: 'تحديد كمقروء',
    markAllAsRead: 'تحديد الكل كمقروء',
    viewAll: 'عرض الكل',
    userProfile: 'الملف الشخصي',
    dataScope: 'نطاق بيانات الفرع',
    viewBranches: 'عرض الفروع',
    addRoot: 'إضافة مستوى رئيسي',
    addChild: 'إضافة فرعي',
    expandAll: 'توسيع الكل',
    collapseAll: 'طي الكل',
    selected: 'المحدد',
    readOnlyCodeHint: 'يتم إنشاء رمز السجل تلقائياً ولا يمكن تعديله بعد الحفظ.',
    requiredFieldHint: 'الحقول المميزة بعلامة (*) حقول إلزامية.',
    bilingualRequiredHint: 'الاسمان العربي والإنجليزي كلاهما إلزامي.',

    // Data Grid & Stats
    totalRecords: 'إجمالي السجلات',
    activeRecords: 'السجلات النشطة',
    inactiveRecords: 'السجلات المعطلة',
    totalUsers: 'إجمالي المستخدمين',
    activeUsers: 'المستخدمون النشطون',
    totalRoles: 'الأدوار المعرفة',
    totalEntities: 'الكيانات القانونية',
    totalBranches: 'الفروع النشطة',
    totalDepartments: 'إجمالي الأقسام',
    totalCostCenters: 'مراكز التكلفة',
    unreadNotifications: 'التنبيهات غير المقروءة',
    activeTemplates: 'القوالب النشطة',
    activeChannels: 'القنوات المفعلة',
    showing: 'عرض',
    of: 'من',
    items: 'عنصر',
    noRecordsFound: 'لم يتم العثور على سجلات',
    noRecordsDesc: 'جرب تعديل معايير البحث أو إضافة سجل جديد.',
    selectBranchToLoadTree: 'يرجى اختيار الفرع لعرض وإدارة الهيكل التنظيمي الخاص به.',

    // Security Module Specific
    secUsersTitle: 'دليل المستخدمين المؤسسي',
    secUsersBreadcrumb: 'الأمن / إدارة المستخدمين',
    secRolesTitle: 'إدارة الأدوار ومصفوفة الصلاحيات (RBAC)',
    secRolesBreadcrumb: 'الأمن / الأدوار والمصفوفة',
    secPermsTitle: 'سجل الصلاحيات المؤسسية',
    secPermsBreadcrumb: 'الأمن / الصلاحيات',
    secPagesTitle: 'سجل الشاشات والمسارات',
    secPagesBreadcrumb: 'الأمن / سجل الشاشات',
    secProfileTitle: 'تفاصيل الملف الشخصي للمستخدم',
    secDataScopeTitle: 'نطاق بيانات الدور وتعيين الفروع',
    userRoles: 'الأدوار المعينة',
    permissionMatrix: 'مصفوفة الصلاحيات',
    permType: 'نوع الصلاحية',
    permNameHint: 'النمط المعتمد: PERM_<MODULE>_<ACTION>',
    autoPermsNotice: 'حفظ هذه الشاشة سينشئ تلقائياً صلاحيات العرض والإضافة والتعديل والحذف.',
    canView: 'عرض',
    canCreate: 'إضافة',
    canUpdate: 'تعديل',
    canDelete: 'حذف',
    activateRole: 'تفعيل الدور',
    deactivateRole: 'تعطيل الدور',
    reactivate: 'إعادة تفعيل',
    deactivate: 'تعطيل',
    employeeId: 'الرقم الوظيفي',
    preferredLang: 'اللغة المفضلة',
    assignedBranch: 'الفرع المعين',
    dataAccessLevel: 'مستوى الوصول للبيانات',
    branchOnly: 'الفرع الخاص فقط',
    branchAndChildren: 'الفرع والفروع التابعة',
    allBranches: 'جميع فروع المنظمة',
    fullNameEn: 'الاسم الكامل (بالإنجليزية)',
    fullNameAr: 'الاسم الكامل (بالعربية)',
    nameEn: 'الاسم (بالإنجليزية)',
    nameAr: 'الاسم (بالعربية)',

    // Organization Module Specific
    orgEntitiesTitle: 'إدارة الكيانات القانونية',
    orgEntitiesBreadcrumb: 'الهيكل التنظيمي / الكيانات القانونية',
    orgBranchesTitle: 'دليل الفروع المؤسسية',
    orgBranchesBreadcrumb: 'الهيكل التنظيمي / الفروع',
    orgRegionsTitle: 'المناطق الجغرافية',
    orgRegionsBreadcrumb: 'الهيكل التنظيمي / المناطق',
    orgDeptsTitle: 'الهيكل الإداري وشجرة الأقسام',
    orgDeptsBreadcrumb: 'الهيكل التنظيمي / الأقسام',
    orgCostCentersTitle: 'شجرة مراكز التكلفة',
    orgCostCentersBreadcrumb: 'الهيكل التنظيمي / مراكز التكلفة',
    orgProfitCentersTitle: 'مراكز الربحية',
    orgProfitCentersBreadcrumb: 'الهيكل التنظيمي / مراكز الربحية',
    orgLocationsTitle: 'المواقع والمستودعات والمرافق',
    orgLocationsBreadcrumb: 'الهيكل التنظيمي / المواقع والمستودعات',
    entityType: 'نوع الكيان',
    branchType: 'نوع الفرع',
    regionType: 'نوع المنطقة',
    costCenterType: 'تصنيف مركز التكلفة',
    siteType: 'نوع المرفق أو الموقع',
    nodeType: 'نوع المستوى (تجميعي / تفصيلي)',
    parentDepartment: 'القسم الرئيسي',
    parentCostCenter: 'مركز التكلفة الرئيسي',
    legalEntity: 'الكيان القانوني',
    branch: 'الفرع',
    summaryNode: 'تجميعي (رئيسي)',
    detailNode: 'تفصيلي (فرعي / ترحيلي)',
    nodeTypeLockedHint: 'لا يمكن تعديل نوع المستوى بعد إنشائه.',
    cascadeDeactivateWarning: 'لا يمكن تعطيل الكيان: توجد فروع تابعة نشطة مرتبطة به.',
    cascadeBranchWarning: 'تعطيل هذا الفرع سيؤثر على الأقسام والمواقع المرتبطة به.',

    // File Service Specific
    fileAttachments: 'المرفقات والوثائق الداعمة',
    uploadFile: 'رفع مستند جديد',
    dragDropFile: 'اسحب وأفلت الملفات هنا أو انقر للتصفح',
    maxFileSize: 'الحد الأقصى لحجم الملف: 5 ميجابايت (PDF, DOCX, PNG, JPG)',
    fileCategory: 'تصنيف الوثيقة',
    fileSize: 'الحجم',
    uploadDate: 'تاريخ الرفع',
    download: 'تحميل',
    uploading: 'جاري رفع المستند...',
    noFilesFound: 'لا توجد مستندات مرفقة حتى الآن',
    noFilesDesc: 'قم برفع العقود، الشهادات، أو الوثائق التشغيلية الداعمة.',

    // Notifications Module Specific
    notifInboxTitle: 'صندوق الإشعارات وسجل التنبيهات',
    notifInboxBreadcrumb: 'مركز الإشعارات / صندوق التنبيهات',
    notifTemplatesTitle: 'إدارة قوالب الإشعارات',
    notifTemplatesBreadcrumb: 'مركز الإشعارات / القوالب',
    notifChannelsTitle: 'تهيئة قنوات الاتصال والإرسال',
    notifChannelsBreadcrumb: 'مركز الإشعارات / القنوات',
    templateCode: 'رمز القالب',
    templateName: 'اسم القالب',
    channel: 'قناة الإرسال',
    module: 'الوحدة / النظام',
    bodyEn: 'نص الرسالة (بالإنجليزية)',
    bodyAr: 'نص الرسالة (بالعربية)',
    templateBodyRequired: 'يجب كتابة نص القالب باللغتين العربية والإنجليزية.',
    availablePlaceholders: 'المتغيرات المتاحة: {{username}}, {{branchName}}, {{otpCode}}, {{unitCode}}',
    editJsonConfig: 'تعديل التهيئة البرمجية (JSON)',
    channelDisabledWarning: 'تعطيل هذه القناة سيوقف كافة الإرساليات الآلية عبر هذه البوابة.',

    // Confirmation & Alerts
    confirmActionTitle: 'تأكيد الإجراء المطلوب',
    confirmDeleteUser: 'هل أنت متأكد من رغبتك في حذف حساب هذا المستخدم نهائياً؟',
    confirmDeactivate: 'هل أنت متأكد من رغبتك في تعطيل هذا السجل؟',
    confirmReactivate: 'هل أنت متأكد من رغبتك في إعادة تفعيل هذا السجل؟',
    confirmDeleteFile: 'هل أنت متأكد من رغبتك في حذف هذا الملف المرفق؟',
    confirmToggleChannel: 'هل أنت متأكد من تغيير الحالة التشغيلية لقناة الاتصال هذه؟',
  },
};

export const useLanguageStore = create<LanguageState>((set, get) => ({
  lang: 'en',
  dir: 'ltr',
  setLanguage: (lang: Language) => {
    const dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.dir = dir;
    document.documentElement.lang = lang;
    set({ lang, dir });
  },
  toggleLanguage: () => {
    const newLang = get().lang === 'en' ? 'ar' : 'en';
    const dir = newLang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.dir = dir;
    document.documentElement.lang = newLang;
    set({ lang: newLang, dir });
  },
  t: (key: string): string => {
    const { lang } = get();
    return translations[lang]?.[key] || translations.en[key] || key;
  },
}));
