// GL DTOs and Models for General Ledger Feature
// @requirement FE-REQ-GL-001
// @task TASK-FE-GL-001

// ── Paged Response (imported from shared) ──────────────────────

export { PagedResponse } from 'src/app/shared/models';

// ── Chart of Accounts ──────────────────────────────────────────

export interface AccountChartDto {
  accountChartPk: number;
  accountChartNo: string;
  accountChartName: string;
  accountType: string;
  accountChartFk: number | null;
  parentAccountName: string | null;
  parentAccountNo: string | null;
  level: number;
  isActive: boolean;
  organizationFk: number;
  organizationSubFk: number | null;
  createdAt?: string;
  createdBy?: string;
  updatedAt?: string | null;
  updatedBy?: string | null;
}

export interface AccountChartTreeNode {
  accountChartPk: number;
  accountChartNo: string;
  accountChartName: string;
  accountType: string;
  level: number;
  isActive: boolean;
  isLeaf: boolean;
  parentPk: number | null;
  organizationFk: number;
  childCount: number;
  children: AccountChartTreeNode[];
}

/**
 * Create request — accountChartNo is auto-generated by the backend.
 */
export interface CreateAccountRequest {
  accountChartName: string;
  accountType: string;
  accountChartFk?: number | null;
  organizationFk: number;
  organizationSubFk?: number | null;
  isActive?: boolean;
}

/**
 * Update request — accountChartNo is immutable (auto-generated) and cannot be changed.
 */
export interface UpdateAccountRequest {
  accountChartName: string;
  accountType: string;
  accountChartFk?: number | null;
  organizationFk: number;
  organizationSubFk?: number | null;
  isActive?: boolean;
}

// ── Eligible Parent LOV ────────────────────────────────────────

/**
 * Lightweight DTO for the eligible-parent LOV.
 * Used in the erp-dual-list component for parent account selection.
 */
export interface EligibleParentAccountDto {
  accountChartPk: number;
  accountChartNo: string;
  accountChartName: string;
  accountType: string;
  isActive: boolean;
}

// ── Search Filters ─────────────────────────────────────────────

export type FilterOperator = 'EQ' | 'NE' | 'GT' | 'GE' | 'LT' | 'LE' | 'LIKE' | 'IN' | 'IS_NULL' | 'IS_NOT_NULL' | 'BETWEEN';

export interface SearchFilter {
  field: string;
  op: FilterOperator;
  value?: string | number | boolean | Array<string | number>;
  value2?: string | number;
}

/**
 * Sort entry matching backend BaseSearchContractRequest.ContractSort
 */
export interface SearchSort {
  field: string;
  direction: 'ASC' | 'DESC';
}

/**
 * Search request body matching backend BaseSearchContractRequest contract.
 * Used by POST /search endpoints.
 */
export interface SearchRequest {
  filters: ContractFilter[];
  sorts?: SearchSort[];
  page: number;
  size: number;
}

/**
 * Contract filter matching backend BaseSearchContractRequest.ContractFilter
 */
export interface ContractFilter {
  field: string;
  operator: string;
  value?: string | number | boolean | Array<string | number>;
}

// ── Lookup Keys (for LookupService) ────────────────────────

/**
 * Central lookup key constants for GL module.
 * Used with LookupService.getLookup(key) / LookupService.getOptions(key).
 *
 * All dropdown data is fetched dynamically from:
 *   GET /api/masterdata/master-lookups/details/options/{key}
 */
export const GL_LOOKUP_KEYS = {
  ACCOUNT_TYPE: 'GL_ACCOUNT_TYPE',
  GL_ACCOUNT_STATUS: 'GL_ACCOUNT_STATUS',
  GL_POSTING_FLAG: 'GL_POSTING_FLAG'
} as const;
